In [1]:
import pandas as pd
import pickle
import bz2

from pathlib import Path
from scipy import stats
import numpy as np

In [2]:
data_path = Path('/data')

In [3]:
with bz2.open(data_path / '09_prepared.pkl.bz2', 'rb') as f:
    df = pickle.load(f)

In [4]:
df.head()

date  ... id_doc_int
0 2020-09-01 17:01:25  ...    1283228
1 2020-09-01 17:35:36  ...    8873113
2 2020-09-01 19:19:21  ...   12712899
3 2020-09-01 21:53:34  ...   21535283
4 2020-09-01 18:42:31  ...     642341

[5 rows x 11 columns]

In [5]:
df.dtypes

date           datetime64[ns]
id_doc                 object
id_order                int64
id_card                object
id_tov                  int64
id_kontr                int64
quantity              float64
sum                   float64
is_green                 bool
id_card_int             int64
id_doc_int              int64
dtype: object

In [6]:
df[['quantity', 'sum']].describe()

quantity           sum
count  4.210086e+07  4.210086e+07
mean   1.427065e+00  1.149112e+02
std    3.101411e+01  1.072201e+02
min   -2.755000e+00 -1.022110e+03
25%    1.000000e+00  4.800000e+01
50%    1.000000e+00  8.900000e+01
75%    1.000000e+00  1.501100e+02
max    5.000000e+03  3.840000e+04

In [7]:
df.groupby(['id_card_int'])['sum'].sum().sort_values(ascending=False)

id_card_int
883386     18259091.85
568930       211154.31
1243870      124131.91
1755035      116411.20
1447941       98215.49
              ...     
365257            0.00
405371            0.00
1843017           0.00
527413            0.00
1871302           0.00
Name: sum, Length: 1358089, dtype: float64

In [8]:
df.loc[df['id_card_int'] == 883386]

date  ... id_doc_int
1221     2020-09-01 13:41:07  ...   16003441
1853     2020-09-01 18:51:35  ...   12641780
1859     2020-09-01 18:04:23  ...   23313124
1925     2020-09-01 18:51:35  ...   12641780
1976     2020-09-01 18:04:23  ...   23313124
...                      ...  ...        ...
42100270 2020-09-30 17:11:56  ...   15650853
42100329 2020-09-30 18:29:17  ...   15143032
42100460 2020-09-30 17:11:56  ...   15650853
42100484 2020-09-30 15:55:39  ...   19534242
42100555 2020-09-30 18:27:16  ...   10843682

[189812 rows x 11 columns]

One of the buyers spent 18 kk in one month. This is strange.

In [9]:
outliers = []
outliers.append(883386)

Using the z-score to find outliers

In [10]:
z_sum = np.abs(stats.zscore(df[['sum']]))

In [11]:
z_sum

array([[0.06445825],
       [0.06445825],
       [0.06492458],
       ...,
       [0.39088971],
       [0.34425664],
       [0.34425664]])

In [12]:
for z in np.where(z_sum>3)[0]: 
    outliers.append(z)

# The same thing for other month

In [13]:
del df
del z

In [ ]:
with bz2.open(data_path / '10_prepared.pkl.bz2', 'rb') as f:
    df = pickle.load(f)

In [ ]:
df.head()

In [ ]:
df.dtypes

In [ ]:
df[['quantity', 'sum']].describe()

In [ ]:
z_sum = np.abs(stats.zscore(df[['sum']]))

In [ ]:
z_sum

In [ ]:
for z in np.where(z_sum>3)[0]:
    outliers.append(z)

In [ ]:
df.groupby(['id_card_int'])['sum'].sum().sort_values(ascending=False)

In [ ]:
df.head()

date  ... id_doc_int
0 2020-09-01 17:01:25  ...    1283228
1 2020-09-01 17:35:36  ...    8873113
2 2020-09-01 19:19:21  ...   12712899
3 2020-09-01 21:53:34  ...   21535283
4 2020-09-01 18:42:31  ...     642341

[5 rows x 11 columns]

In [ ]:
df.dtypes

date           datetime64[ns]
id_doc                 object
id_order                int64
id_card                object
id_tov                  int64
id_kontr                int64
quantity              float64
sum                   float64
is_green                 bool
id_card_int             int64
id_doc_int              int64
dtype: object

In [ ]:
df[['quantity', 'sum']].describe()

quantity           sum
count  4.210086e+07  4.210086e+07
mean   1.427065e+00  1.149112e+02
std    3.101411e+01  1.072201e+02
min   -2.755000e+00 -1.022110e+03
25%    1.000000e+00  4.800000e+01
50%    1.000000e+00  8.900000e+01
75%    1.000000e+00  1.501100e+02
max    5.000000e+03  3.840000e+04

In [ ]:
z_sum = np.abs(stats.zscore(df[['sum']]))

In [ ]:
z_sum

array([[0.06445825],
       [0.06445825],
       [0.06492458],
       ...,
       [0.39088971],
       [0.34425664],
       [0.34425664]])

In [ ]:
for z in np.where(z_sum>3)[0]:
    outliers.append(z)

In [ ]:
df.groupby(['id_card_int'])['sum'].sum().sort_values(ascending=False)

id_card_int
883386     18259091.85
568930       211154.31
1243870      124131.91
1755035      116411.20
1447941       98215.49
              ...     
365257            0.00
405371            0.00
1843017           0.00
527413            0.00
1871302           0.00
Name: sum, Length: 1358089, dtype: float64

In [ ]:
df.loc[df['id_card_int'] == 883386]

date  ... id_doc_int
1221     2020-09-01 13:41:07  ...   16003441
1853     2020-09-01 18:51:35  ...   12641780
1859     2020-09-01 18:04:23  ...   23313124
1925     2020-09-01 18:51:35  ...   12641780
1976     2020-09-01 18:04:23  ...   23313124
...                      ...  ...        ...
42100270 2020-09-30 17:11:56  ...   15650853
42100329 2020-09-30 18:29:17  ...   15143032
42100460 2020-09-30 17:11:56  ...   15650853
42100484 2020-09-30 15:55:39  ...   19534242
42100555 2020-09-30 18:27:16  ...   10843682

[189812 rows x 11 columns]

In [ ]:
outliers = []
outliers.append(883386)

#And again



In [ ]:
del df
del z

In [4]:

with bz2.open(data_path / '11_prepared.pkl.bz2', 'rb') as f:
    df = pickle.load(f)

In [5]:
df.head()

date  ... id_doc_int
0 2020-11-01 15:29:01  ...    3121751
1 2020-11-01 12:41:10  ...   22047017
2 2020-11-01 13:17:09  ...    6419825
3 2020-11-01 12:31:31  ...   10284541
4 2020-11-01 13:06:15  ...   10424967

[5 rows x 11 columns]

In [6]:
df.dtypes

date           datetime64[ns]
id_doc                 object
id_order                int64
id_card                object
id_tov                  int64
id_kontr                int64
quantity              float64
sum                   float64
is_green                 bool
id_card_int             int64
id_doc_int              int64
dtype: object

In [7]:
df[['quantity', 'sum']].describe()

quantity           sum
count  4.649662e+07  4.649662e+07
mean   1.381354e+00  1.195184e+02
std    2.943611e+01  1.144673e+02
min    0.000000e+00  0.000000e+00
25%    1.000000e+00  5.200000e+01
50%    1.000000e+00  9.200000e+01
75%    1.000000e+00  1.530000e+02
max    5.000000e+03  1.478400e+04

In [8]:
z_sum = np.abs(stats.zscore(df[['sum']]))

In [9]:
z_sum

array([[0.10080083],
       [0.1006261 ],
       [0.06568161],
       ...,
       [0.74709915],
       [0.28376328],
       [1.01791895]])

In [19]:
for z in np.where(z_sum>3)[0]:
    outliers.append(z)

In [12]:
df.groupby(['id_card_int'])['sum'].sum().sort_values(ascending=False)

id_card_int
883386     22018356.77
1577248     1279932.55
1028081      117739.34
356029       116052.43
588107       112809.07
              ...     
1801523           0.00
1393872           0.00
1658568           0.00
1084788           0.00
1013965           0.00
Name: sum, Length: 1335358, dtype: float64

In [13]:
df.loc[df['id_card_int'] == 883386]

date  ... id_doc_int
145      2020-11-01 18:10:40  ...    9943680
544      2020-11-01 18:10:40  ...    9943680
1022     2020-11-01 18:08:23  ...   13314883
1068     2020-11-01 17:58:02  ...    8864097
1257     2020-11-01 18:08:23  ...   13314883
...                      ...  ...        ...
46495920 2020-11-30 17:39:59  ...   15823137
46496028 2020-11-30 20:07:31  ...   15684187
46496039 2020-11-30 17:39:59  ...   15823137
46496194 2020-11-30 11:16:22  ...   21960612
46496309 2020-11-30 19:42:49  ...    1912154

[228012 rows x 11 columns]

In [14]:
outliers.append(883386)

Saving

In [23]:
outliers_df = pd.DataFrame(list(set(outliers)), columns=['id_card_int'])
with bz2.open('outliers.bz2', 'wb') as f:
    pickle.dump(outliers_df, f, protocol=4)